//
//  main.c
//  Exe6.33
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(PALINDROMI) UN PALINDROMO E' UNA STRINGA CHE SI LEGGE ALLO STESSO MODO DA SINISTRA A DESTRA E DA DESTRA A SINISTRA. ALCUNI ESEMPI DI PALINDROMI SONO: "RADAR", "ABLE WAS I ERE I SAW ELBA" E "A MAN A PLAN A CANAL PANAMA". SCRIVETE UNA FUNZINE RICORSIVA testPalindrome CHE RESTITUISCA 1, QUALORA LA STRINGA IMMAGAZZINATA NEL VETTORE SIA UN PALINDROMO, E 0 IN CASO CONTRARIO. LA FUNZIONE DOVRÀ IGNORARE GLI SPAZI E LA PUNTEGGIATURA EVENTUALMENTE PRESENTI NELLA STRINGA.
*/
