//
//  main.c
//  Exe7.18
//
//  Created by Francesco Parrucci on 14/04/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
(PROGRAMMAIZONE IN LINGUAGGIO MACCHINA) CREEREMO ORA UN COMPUTER CHE CHIAMEREMO SIMPLETRON. COME IL SUO NOME LASCIA INTENDERE 
SI TRATTA DI UNA MACCHINA SEMPLICE, MA COME VEDREMO PRESTO ANCHE POTENTE. IL SIMPLETRON ESEGUIRÀ DEI PROGRAMMI SCRITTI NELL'
UNICO LINGUAGGIO CHE SIA IN GRADO DI COMPRENDERE DIRETTAMENTE, VALE A DIRE IL LINGUAGGIO MACCHINA SIMPLETRON, CHE ABBREVIAMO
IN LMS. IL SIMPLETRON CONTIENE UN ACCUMULATORE UN "REGISTRO SPECIALE" IN CUI SARANNO INSERITE TUTTE LE INFORMAZIONI. PRIMA
CHE IL SIMPLETRON POSSA UTILIZZARLE PER I CALCOLI O PER ESAMINARLE IN VARI MODI. TUTTE LE INFORMAIZONI SARANNO MANIPOLATE 
ALL'INTERNO DEL SIMPLETRON COME PAROLE. UNA PAROLA È UN NUMERO DECIMALE DI QUATTRO CIFRE CON SEGNO, COME +3364, -1293, +0007,
-0001, ECC. IL SIMPLETRON È EQUIPAGGIATO CON UNA MEMORIA DI 100 PAROLE ALLE QUALI FAREMO RIRERIMENTO ATTRAVERSO I LORO NUMERI
DI LOCAIZONE 00, 01, ....90.
PRIMA DI POTER ESEGUIRE UN PROGRAMMA LMS DOVREMO CARICARLO O IMMETTENDO NELLA MEMORIA. LA PRIMA ISTRUZIONE (O COMANDO) DI OGNI
PROGRAMMA LMS SARÀ SEMPRE CARICATA NELLA POSIZIONE 00.
OGNI ISTRUZIONE SCRITTA IN LMS OCCUPERÀ UNA PAROLA NELLA MEMORIA DEL SIMPLETRON E DI CONSEGUENZA , CORRISPONDERÀ, A UN NUMERO
DECIMALE DI QUATTRO CIFRE CON SEGNO. OVVIAMENTE IL SEGNO DI OGNI ISTRUZIONE LMS SARÀ SEMPRE QUELLO POSITIVO, MENTRE QUELLI DELLE
PAROLE CHE CONTENGONO DEI DATI POTRANNO ESSERE POSITIVI O NEGATIVI. OGNI LOCAZIONE DELLA MEMORIA DEL SIMPLETRON POTRÀ CONTENERE 
UN'ISTRUZIONE, IL VALORE DI UN DATO UTILIZZATO DAL PROGRAMMA, OPPURE UN'AREA DI MEMORIA INUTILIZZATA (E QUINDI INDEFINITA). LE 
PRIME DUE CIFRE DI OGNI ISTRUIZONE LMS CORRISPONDERANNO AL CODICE DELL'OPERAZIONE CHE DOVRÀ ESSERE ESEGUITA. I CODICI DELLE 
OPERAZIONI LMS SONO RIASSUNTI NELLA FIGURA 7.31
------------------------------------------------------------------------------------------------------------------------------
CODICE DELL'OPERAIZONE				SIGNIFICATO
------------------------------------------------------------------------------------------------------------------------------
OPERAZIONE DI INPUT / OUTPUT :

#DEFINE READ 10					LEGGE UNA PAROLA DAL TERMINALE E LA IMMAGAZZINA IN UNA SPECIFICA LOCAIONE DI
						MEMORIA.

#DEFINE WRITE 11				SCRIVE SUL TERMINALE LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAIZONE DI MEMORIA.

OPERAZIONI DI CARICAMENTO / IMMAGAZZINAMENTO :

#DEFINE LOAD 20 				CARICA NELL'ACCUMULATORE LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAZIONE DI MEMORIA.

#DEFINE STORE 21				ARCHIVIA IL CONTENUTO DELL'ACCUMULATORE IN UNA SPECIFICA LOCAZIONE DI MEMORIA.

OPERAZIONI ARITMETICHE:

#DEFINE ADD 30					AGGIUNGE LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAIZONE DI MEMORIA A QUELLA CONTENUTA
						NELL'ACCUMULATORE (LASCIANDO IN QUESTO IL RISULTATO)

#DEFINE SUBTRACT 31				SOTTRAE LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAZIONE DI MEMORIA DA QUELLA CONTENUTA
						NELL'ACCUMULATORE (LASCIANDO IN QUESTO IL RISULTATO)

#DEFINE DIVIDE 32				DIVIDE LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAZIONE DI MEMORIA PER QUELLA CONTENUTA 
						NELL'ACCUMULATORE (LASCIANDO IN QUESTO IL RISULTATO)

#DEFINE MULTIPLY 33				MOLTIPLICA LA PAROLA CONTENUTA IN UNA SPECIFICA LOCAIZONE DI MEMORIA PER QUELLA CONTENUTA
						NELL'ACCUMULATORE (LASCIANDO IN QUESTO IL RISULTATO).

OPERAZIONI DI TRASFERIMENTO DEL CONTROLLO:

#DEFINE BRANCH 40 				SALTA A UNA SPECIFICA LOCAZIONE DI MEMORIA

#DEFINE BRANCHNEG 41				SALTA A UNA SPECIFICA LOCAIZONE DI MEMORIA, SE L'ACCUMULATORE UN VALORE NEGATIVO.

#DEFINE BRANCHZERO 42				SALTA A UNA SPECIFICA LOCAIZONE DI MEMORIA, SE L'ACCUMULATORE CONTIENE UN VALORE UGUALE A ZERO.

#DEFINE HALT 43					FERMA L'ESECUZIONE DEL PROGRAMMA
--------------------------------------------------------------------------------------------------------------------------------------------

C) LEGGETE UNA SERIE DI NUMERI E DETERMINATE E VISUALIZZATE QUELLO MAGGIORE. IL PRIMO NUMERO LETTO INDICHERÀ QUANTI VALORI DOVRANNO ESSERE 
   ELABORATI.

*/
