//
//  main.c
//  Exe6.27
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(LE OTTO REGINE: APPROCCI BRUTALI) IN QUESTO ESERCIZIO SVILUPPERETE DIVERSI APPROCCI BRUTALI PER RISOLVERE IL PROBLEMA DELLE OTTO REGINE INTRODOTTO NELL'ESERCIZIO 6.26.
A) RISOLVETE IL PROVLEMA DELLE OTTO REGINE, UTILIZZANDO LA TECNICA DELLA FORZA BRUTA CASUALE SVILUPPATA NELL'ESERCIZIO 6.25

B) USATE UNA TECNICA ESAUSTIVA: TENTATE CIOE' TUTTE LE POSSIBILI COMBINAZIONI PER IL POSIZIONAMENTO DELLE OTTO REGINE SULLA SCACCHIERA.

C) PER QUALE MOTIVO PENSATE CHE L'APPROCCIO ESAUSTIVO CON LA FORZA BRUTA NON SIA APPROPRIATO PER RISOLVERE IL PROBEMA DEL GIRO DEL CAVALLO?

D) CONFORNTATE E CONTRASTATE I DUE APPROCCI BRUTALI, CAUALE E ESAUSTIVO, IN GENERALE.
*/
