//
//  main.c
//  Exe5.39
//
//  Created by Francesco Parrucci on 31/01/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
(LE TORRI DI HANOI) OGNI INFORMATICO IN ERBA DOVRA' VENIRE ALLE PRESE CON CERTI PROBLEMI CLASSICI E LE TORRI DI HANOI E' UNO 
DEI PIU' FAMOSI DI QUESTI. LA LEGGENDA NARRA CHE , IN UN TEMPOIO DELL'ESTREMO ORIENTE , ALCUNI PRETI STAVANO TENTANDO DI 
MUOVERE UNA PILA DI DISCHI DA UN PALETTO A UN ALTRO. LA PILA INIZIALE AVEVA 64 DISCHI INFILATI SU UN LAPETTO E ORDINATI IN 
MISURA DECRESCENTE DAL BASSO ALL'ALTO. I PRETI STAVANO TENTANDO DI MUOVERE LA PILA DA QUESTO A UN SECONDO PALETTO, RISPETTANDO 
DELLE REGOLE SECONDO LE QUALI: POTEVA ESSERE MOSSO ESATTAMENTE UN DISCO PER VOLTA E IN NESSUN MOMENTO UN DISCO PIU' GRANDE 
POTEV ESSERE  SISTEMATO SU UNO PIU' PICCOLO. ERA DISPONIBILE UN TERZO PALETTO PER RIPORRE TEMPORANEAMENTE I DISCHI. SECONDO LA 
LEGGENDA, QUALORA I PRETI AVESSERO COMPLETATO IL LORO COMPITO, SAREBBE GIUNTA LA FINE DEL MONDO, PERCIO' NON ABBIAMO MOLTO 
INTERESSE NEL FACILITARE I LORO SFORZI.
SUPPONIAMO CHE I PRETI STANO TENTANDO DI MUOVERE IDISCHI DAL PALETTO 1 AL 3 . VOGLIAMO SVILUPPARE UN ALGORITMO CHE VISUALIZZI
L'ESATTA SEQUENZA DI TRASFERIMENTI DI PALETTO DISCO PER DISCO. SE DOVESSIMO AFFRONTARE QUESTO PROBLEMA CON I METODI 
CONVENZIONALE, CI RITROVEREMMO PRESTO DISPERATAMENTE INGUARBUGLIATI NELLA MANIPOLAZIONE DEI DISCHI. SE INVECE AFFRONTIAMO IL 
PROBLEMA TENENDO IN MENTE LA RICORSIONE, ESSO DIVENTERA' IMMEDIATAMENTE TRATTABILE. LO SPOSTAMENTO DI N DISCHI PORTRA ESSERE 
VISTO COME LO SPOSTAMENTO DI SOLI N-1 DISCHI(E QUINDI LA RICORSIONE) COME SEGUE:
 
        1 MUOVERE N - 1 DISCHI DAL PALETTO 1 AL 2, UTILIZZANDO IL 3 COME AREA DI DEPOSITO TEMPORANEA.
        2 MUOVERE L'ULTIMO DISCO (IL PIU GRANDE ) DAL PALETTO 1 AL PALETTO 3
        3 MUOVERE GLI N - 1 DISCHI DAL PALETTO 2 AL 3, UTILIZZANDO IL PALETTO 1 COME AREA DI DEPOSITO TEMPORANEA.
 
 IL PROCESSO TERMINERA' QUANDO L'ULTIMO COMPITO RICHIEDERA' LO SPOSTAMENTO DI N = 1 DISCHI, OVVEROSIA IL CASO DI BASE. CIO' 
 SARA' ESEGUITO SEMPLICEMENTE SPOSTANDO IL DISCO, SENZA LA NECESSITA' DI UN'AREA DI DEPOSITO TEMPORANEA.
 SCRIVERE UN PROGRAMMA CHE RISOLVA IL PROBLEMA DELLE TORRI DI HANOI. UTILIZZATE UNA FUNZIONE RICORSIVA CON QUATTRO PARAMETRI:
 
 1 IL NUMERO DEI DISCHI DA MUOVERE
 2 IL PALETTO SUL QUALE QUESTI DISCHI SARANNO INIZIALMENTE INFILATI.
 3 IL PALETTO SULA QUALE QUESTA PILA DI DISCHI DOVRA' ESSERE SPOSTATA
 4 IL PALETTO CHE DOVRA' ESSERE UTILIZZATO COME AREA DI DEPOSITO
 
 
 IL VOSTRO PROGRAMMA DOVRA' VISUALIZZARE LE ISTRUZIONI PRECISE NECESSARIE PER LO SPOSTAMENTO DEI DISCHI DAL PALETTO DI PARTENZA 
 A QUELLO DI DESTINAZIONE. PER ESEMPIO, PER MUOVERE UNA PILA DI TRE DISCHI DAL PALETTO 1  AL PALETTO 3, IL VOSTRO PROGRAMMA 
 DOVRA' VISUALIZZARE LA SEGUENTE SERIE DI MOSSE:
 
 1 -> 3(QUESTO SIGNIFICA MUOVERE UN DISCO DAL PALETTO 1 AL PALETTO 3)
 1 -> 2
 3 -> 2
 1 -> 3
 2 -> 1
 2 -> 3
 1 -> 3
 
 */


#include <stdio.h>

void hanoi(int , int, int, int);

int main(int argc, const char * argv[]) {
    // insert code here...
    int number;
    
    printf("\nInserire il numero di dischi da muovere:");
    scanf("%d", &number);
    
    hanoi(1,2,3,number);
    
    printf("\nHello, World!\n");
    return 0;
}

void hanoi(int uno , int due, int tre, int n){
    if (n == 1)
        printf("\n%d -> %d", uno , tre);
    else{
        hanoi(uno, tre, due, n - 1);
        printf("\n%d -> %d",uno,tre);
        hanoi(due, uno, tre, n - 1);
        
    }
}