//
//  main.c
//  Exe6.32
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(ORDINAMENTO PER SELEZIONE) UN ORDINAMENTO PER SELEZIONE RICERCHERA' IN UN VETTORE L'ELEMENTO PIU' PICCOLO E, QUANDO L'AVRA' INDIVIDUATO, LO SCAMBIERA' DI POSTO CON IL PRIMO ELEMENTO DEL VETTORE. IL PROCESSO SI RIPETERA' PER IL SOTTOVETTORE CHE COMINCIA CON IL SECONDO ELEMENTO DEL VETTORE. OGNI PASSAGGIO SUL VETTORE FARÀ IN MODO CHE UN ELEMENTO SIA SIASTEMATO NELLA POSIZIONE APPROPRIATA. QUESTO ORDINAMENTO RICHIEDE CAPACIATÀ DI ELABORAZIONE SIMILI DELL'ORDINAMENTO A BOLLE PER UN VETTORE DI N ELEMENTI, DOVRANNO ESSERE ESEGUITI N - 1 PASSAGGI E PER OGNI SOTTOVETTORE DOVRANNO ESSERE COMPIUTI N - 1 CONFRONTI PER INDIVIDUAREE IL VALORE PIU' PICCOLO. IL VETTORE RISULTERÀ ORDINATO NEL MOMENTO IN CUI IL SOTTOVETTORE DA ELABORARE CONTERRÀ UN SOLO ELEMENTO. SCRIVETE UNA FUNZIONE RICORSIVA selectionSort CHE IMPLEMENTI QUESTO ALGORITMO.
*/
