//
//  main.c
//  Exe6.39
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(TROVARE IL VALORE MINIMO IN UN VETTORE) SCRIVETE UNA FUNZIONE RICORSIVA recursiveMinimum CHE RICEVA COME ARGOMENTI UN VETTORE DI INTERI E LA SUA DIMENSIONE E RESTITUISCA L'ELEMENTO PIU PICCOLO DEL VETTORE. LA FUNZIONE DOVRÀ TERMINARE LA PROPRIA ELABORAZIONE E RESTITUIRE IL CONTROLLO A QUELLA CHIAMANTE, QUANDO AVRÀ RICEVUTO UN VETTORE CHE CONTENGA UN SOLO ELEMENTO. 
*/
