//
//  main.c
//  Exe6.34
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(RICERCA LINEARE) MODIFICATE IL PROGRAMMA DELLA FIGURA 6.18, IN MODO DA UTILIZZARE UNA FUNZIONE RICORSIVA linearSearch CHE ESEGUAUNA RICERCA LINEARE ALL'INTERNO DEL VETTORE.
LA FUNZIONE DOVRA' RICEVERE COME ARGOMENTI UN VETTORE DI INTERI E LA SUA DIMENSIONE. NEL CASO CHE LA CHIAVE DI RICERCA SIA STATA RITROVATA, RESTITUIRETE L'INDICE DEL VETTORE, ALTRIMENTI -1.
*/

