//
//  main.c
//  Exe6.24
//
//  Created by Francesco Parrucci on 02/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
(IL GIRO DEL CAVALLO) UNO DEI PROBLEMI PIU INTERESSANTI PER GLI APPASSIONATI DEL GIOCO DEGLI SCACCHI D' QUELLO DEL GIRO DEL CAVALLO, PROPOSTO ORIGINARIAMENTE DAL MATEMATICO EULERO. LA QUESIONE Eì QUESTA :  PUO' IL PEZZO DEGLI SCACCHI CHIAMATO CAVALLO MUVERSI IN UNA SCACCHIERA VUOTA, VISITANDO UNA SOLA VOLTA OGNUNA DELLE 64 CASELLE? STUDIEREMO APPROFONDITAMENTE QUESTO PROBLEMA AFFASCINANTE. IL CAVALLO COMPIE DELLE MOSSE A FORMA DI L: DUE CASELLE IN UNA DIREZIONE E UNA IN UNA DIRETTRICE PERPENDICOLARE A QUELLA PRECEDENTE. NE CONSEGUE CHE, DA UNA CASELLA CENTRALE DI UNA SCACCHIERA VUOTA, IL CAVALLO POTRA' ESEGUIRE OTTO DIFFERENTI MOSSE (NUMERATE DA 0 A 7). 
 
 A) DISEGNATE UNA SCACCHIERA 8 PER 8 SU UN FOGLIO SU UN FOGLIO DI CARTA E TENTATE DI PORTARE A TERMINE MANUALMENTE UN GIRO DEL CAVALLO. INSERITE UN 1 NELLA PRIMA CASELLA IN CUI VI MUOVERETE, UN 2 NELLA SECONDA, UN 3 NELLA TERZA, ECC. PRIMA DI INCOMINCIARE IL GIRO, PROVATE A FARE UNA STIMA DELLE MOSSE CHE RIUSCIRETE A COMPIERE, RICORDANDO CHE UN GIRO COMPLETO CONSISTE DI 64 MOSSE. DOVE SIETE ARRIVATI ? VI SIETE AVVICINATI ALLA VOSTRA STIMA?

B) ORA SVILUPPEREMO UN PROGRAMMA CHE MUOVERA' IL CAVALLO IN GIRO PER LA SCACCHIERA. LA SCACCHIERA STESSA SARA' RAPPRESENTATA DALLA MATRICE 8 PER 8 BOARD. OGNUNA DELLE CASELLE SARA' INIZIALMENTE AZZERATA. DESCIVEREMO OGNUNA INIZIALMENTE AZZERATA. DESCIVEREMO OGNUNA DELLE OTTO POSSIBILI MOSSE SCINDENDOLE NELLE LORO COMPONENTI ORIZZONTALI E VERTICALI. PER ESEMPIO , UNA MOSSA COME LA ' MOSTRATA NELLA FIGURA  6.24 POTRAè ESSERE SCOMPOSTA IN UN MOVIMENTO ORIZZONTALE (DUE CASELLE A DESTRA) E IN UNO SPOSTAMENTO VERTICALE (UNA CASELLA A SINISTRA) E DI UNO SPOSTAMENTO VERTICALE (DUE CASELLE IN ALTO). LE MOSSE ORIZZONTALI A SINISTRA E QUELLE VERTICALI VERSO L'ALTO SARANNO INDICATE CON DEI NUMERI NEGATIVI . LE OTTO MOSSE POTRANNO ESSETE DESCRITTE DA DUE VETTORI UNIDIMENSIONALI, HORIZONTAL E VERICAL , COME SEGUE:
 
 HORIZONTAL[0] = 2
 HORIZONTAL[1] = 1
 HORIZONTAL[2] = -1
 HORIZONTAL[2] = -2
 HORIZONTAL[2] = -2
 HORIZONTAL[2] = -1
 HORIZONTAL[2] = 1
 HORIZONTAL[2] = 1
 
#include <stdio.h>

int main(int argc, const char * argv[]) {
    // insert code here...
    printf("Hello, World!\n");
    return 0;
}
