//
//  main.c
//  Exe6.29
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
(IL GIRO DEL CAVALLO: VERIFICA DEL GIRO CICLICO) NEL GIRO DEL CAVALLO, DEFINIREMO COMPLETO UN DIRO IN CUI IL CAVALLO AVRA' EFFETTUATO 64 MOSSE, TOCCANDO OGNI CASELLA DELLA SCACCHIERA UNA SOLA VOLTA- DEFINIREMO CICLICO UN GIRO COMPLETO IN CUI LA 64° POSIZIONE DISTI UNA MOSSA DA QUELLA IN CUI IL CAVALLO HA COMINCIATO IL GIRO. MODIFICATE IL PROGRAMMA DEL GIRO DEL CAVALLO CHE AVETE SCRITTO NELL'ESERCITIO 6.24, IN MODO DA VERIFICARE SE UN GIRO COMPLETO SIA ANCHE CICLICO.
*/
