//
//  main.c
//  Exe7.17
//
//  Created by Francesco Parrucci on 13/04/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
(SIMULAZIONE: LA TARTARUGA E LA LEPRE) IN QUESTO ESERCIZIO RICREERETE UNO DEI MOMENTI STORICI PIÙ IMPORTANTI
, VALE A DIRE LA CLASSICA CORSA TRA LA TARTARUGA E LA LEPRE. UTILIZZERETE LA GENERAZIONE DEI NUMERI CASUALI
PER SVILUPPARE UNA SIMULAZIONE DI QUESTO MEMORABILE EVENTO.
I NOSTRI CONTENDENTI COMINCERANNO LA LORO CORSA NELLA 'CASELLA 1" DELLE 70 CHE COMPONGONO IL PERCORSO DELLA
GARA. OGNI CASELLA RAPPRESENTA UNA DELLE POSIZIONI POSSIBILI LUNGO IL PERCORSO DELLA GARA. LA LINEA DI ARRIVO
È NELLA CASELLA NUMERO 70. IL PRIMO CONTENDENTE CHE AVRÀ RAGGIUNTO O SUPERATO LA CASELLA 70 SARÀ PREMIATO CON
UN SECCHIO  DI CAROTE E LATTUGHE FRESCHE. IL PERCORSO SI INERPICA SERPEGGIANDO SUL FIANCO DI UNA MONTAGNA SDRUC
CIOLEVOLE, PERCIÒ I CONTENDENTI POTRANNO PERDERE TERRENO DI QUANDO IN QUANDO.

C'È UN OROLOGIO CHE SCANDISCE OGNI SECONDO. AD OGNI TIC DELL'OROLOGIO IL VOSTRO PROGRAMMA DOVRÀ AGGIUSTARE LA 
POSIZIONE DEGLI ANIMALI SECONDO LE SEGUENTI REGOLE:
--------------------------------------------------------------------------------------------------------------
ANIMALE 	TIPO DI MOSSA		PERCENTUALE DI TEMPO		MOSSA EFFETTIVA
--------------------------------------------------------------------------------------------------------------
TARTARUGA	ARRANCATA RAPIDA	50%				3 CASELLE A DESTRA
		SCIVOLONE		20%				6 CASELLE A SINISTRA
		ARRANCATA LENTA		30%				1 CASELLA A DESTRA

LEPRE		DORMITA			20%				NESSUNA MOSSA
		SALTO LUNGO		20%				9 CASELLE A DESTRO
		SCIVOLONE LUNGO		10%				12 CASELLE A SINISTRA
		SALTO CORTO		30%				1 CASELLA DESTRA
		SCIVOLONE CORTO		20%				2 CASELLE A SINISTRA
---------------------------------------------------------------------------------------------------------------

UTILIZZATE LE VARIABILI PER MANTENERE TRACCIA DELLE POSIZIONI DEGLI ANIMALI (OVVEROSIA DEI NUMERI DA 1 A 70).
FATE PARTIRE OGNI ANIMALE DALLA POSIZIONE 1 (VALE A DIRE DALLE "GABBIE DI PARTENZA"). RIPORTATE NELLA CASELLA
1 L'ANIMALE CHE DOVESSE EVENTUALMENTE SCIVOLARE INDIETRO IN UNA POSIZIONE PRECEDENTE A QUELLA.
GENERATE LE PERCENTUALI MOSTRATE NELLA TABELLA PRECEDENTE PRODUCENDO UN INTERO CASUALE I COMPRESO NELL'INTERVALLO
1 = I = 10. NEL CASO DELLA TARTARUGA ESEGUIRETE UNA "ARRANCATA RAPIDA" QUANDO 1 = I = 5, UNA "SCIVOLATA" QUANDO 
6 = I = 7 O UNA "ARRANCATA LENTA" QUANDO 8 = I = 10. UTILIZZATE UNA TECNICA SIMILE PER FAR CORRERE LA LEPRE.

COMINCIATE LA GARA VISUALIZZANDO:

BANG !!! 
AND THE'RE OFF !!!

IN SEGUITO, PER OGNI TIC DELL'OROLOGIO (OVVEROSIA PER CIASCUNA RIPETIZIONE DEL CICLO), VISUALIZZERETE UNA LINEA DI
70 POSIZIONI CHE MOSTRI UNA LETTERA T IN QUELLA DELLA TARTARUGA E UNA L  IN QUELLA DELLA LEPRE. DI QUANDO IN QUANDO.
, I CONTENDENTI SI RITROVERANNO NELLA STESSA CASELLA. IN TAL CASO LA TARTARUGA MORDERÀ LA LEPRE E IL VOSTRO PROGRAMMA
DOVRÀ VISUALIZZARE OUCH!!! IN QUELLA POSIZIONE. TUTTE LE POSIZIONI DI VISUALIZZAZIONE DIVERSE DA T, L OD OUCH!!! 
DOVRANNO RESTARE VUOTE. 
DOPO CHE OGNI LINEA SARÀ STATA VISUALIZZATA, CONTROLLERETE SE UNO DEI DUE ANIMALI ABBIA RAGGIUNTO O SUPERATO LA CASELLA
70. IN CASO AFFERMATIVO VISUALIZZERETE IL NOME DEL VINCITORE E TERMINERETE LA SIMULAZIONE. 
NEL CASO CHE ABBIA VINTO LA TARTARUGA VISUALIZZERETE "TORTOISE WINS !!! YAY!!!". NEL CASO CHE ABBIA VINTO LA LEPRE 
VISUALIZZERETE "HARE WINS. YUCH." NEL CASO CHE ENTRAMBI GLI ANIMALI TAGLIASSERO IL TRAGUARDO NELLO STESSO TIC DELL'
OROLOGIO, POTRESTE FAVORIRE LA TARTARUGA (POVERINA), OPPURE POTRESTE VISUALIZZARE "IT'S A TIE." 
NEL CASO CHE NESSUNO DEI DUE ANIMALI ABBIA ANCORA VINTO, ESEGUITE UN'ALTRA VILTA IL CICLO PER SIMULARE IL SUCCESSIVO 
TIC DELL'OROLOGIO. RADUNATE UN GRUPPO DI TIFOSI CHE ASSISTANO ALLA GARA, QUANDO SARETE PRONTI A MANDARE IN ESECUZIONE
IL VOSTRO PROGRAMMA. IL COINVOLGIMENTO DEL VOSTRO PUBBLICO VI SORPRENDERÀ.
*/


#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void waitFor(unsigned int secs);
void see(char [], int, char);
int mossa(char);
void seethem(int, int);

int main()
{
 char v[71];
 int tartaruga = 1, lepre = 1;
 

 printf("\nBANG!!!\n");
 printf("AND THE'RE OFF !!!\n\n\n"); 
 seethem(tartaruga, lepre);

 while(tartaruga < 70 && lepre < 70){

    waitFor(1);

    tartaruga += mossa('T');

    if(tartaruga <= 0)
	tartaruga = 1;

    lepre += mossa('L');

    if(lepre <= 0)
 	lepre = 1;
   
    seethem(tartaruga, lepre);

    if(lepre == tartaruga)
	printf("\nOUGH!!!\n");
    
 }

 if(tartaruga > lepre)
	printf("\nTartaruga WINS !!!\n");
 else 
	printf("\nLepre WINS !!!\n");

 return 0;
}

void waitFor (unsigned int secs) {
    unsigned int retTime = time(0) + secs;   // Get finishing time.
    while (time(0) < retTime);               // Loop until it arrives.
}

int mossa(char type){
   
   int value, i = 1 + rand() % 10;	

	if(type = 'T'){
	  if(i >= 1 && i <= 5) 		 // ARRANCATA RAPIDA 50% 3 CASELLE A DESTRA
	    value = 3;
	  else if(i >= 6 && i <= 7)	 // SCIVOLONE
	    value = -6;
	  else				 // ARRANCATA LENTA
            value = 1; 

	}else{ 				 //if(type = 'L'){

	  if(i >= 1 && i <= 2) 		 // DORMITA
	    value = 0;
	  else if(i >= 3 && i <= 4) 	 // SALTO LUNGO
	    value = 9;
	  else if(i == 5) 		 // SCIVOLONE
	    value = -12;
	  else if(i >= 6 && i <= 8) 	 // SALTO CORTO
	    value = 1;
          else 				 // SCIVOLONE CORTO
	    value = -2;

	}
	
   return value;
}

void seethem(int tartaruga, int lepre){
	
  int x;

  for(x = 1 ; x <= 70 ; x++){
	tartaruga == x ? printf("T") : printf("_");
  }
	
  printf("\n");

  for(x = 1 ; x <= 70 ; x++){
        lepre == x ? printf("L") : printf("_");
  }

  printf("\n");


}
