//
//  main.c
//  Exe5.40
//
//  Created by Francesco Parrucci on 01/02/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*
 OGNI PROGRAMMA CHE POSSA ESSERE IMPLEMENTATO IN MODO RICORSIVO POTRA' ESSERE SOSTRUITO IN MANIERA ITERATIVA, SEBBENE A VOLTE 
 CON MAGGIORI DIFFICOLTA' E MINOR CHIAREZZA. CERCATE DI SCRIVERE UNA VERSIONE ITERATIVA DELLE TORRI DI HANOI. QUALORA VI 
 RIUSCITE CONFRONTATE LA VOSTRA VERSIONE ITERATIVA CON QUELLA RICORSIVA CHE AVETE SVILUPPATO NELL'ESERCIZIO 5.39 ANALIZZATE I 
 PROBLEMI DI EFFICIENZA, DI CHIAREZZA E LA VOSTRA CAPACITA' NEL DIMOSTRARE LA CORRETTEZZA DEI PROGRAMMI.
 
 SUPPONIAMO CHE I PRETI STANO TENTANDO DI MUOVERE IDISCHI DAL PALETTO 1 AL 3 . VOGLIAMO SVILUPPARE UN ALGORITMO CHE VISUALIZZI
 L'ESATTA SEQUENZA DI TRASFERIMENTI DI PALETTO DISCO PER DISCO. SE DOVESSIMO AFFRONTARE QUESTO PROBLEMA CON I METODI
 CONVENZIONALE, CI RITROVEREMMO PRESTO DISPERATAMENTE INGUARBUGLIATI NELLA MANIPOLAZIONE DEI DISCHI. SE INVECE AFFRONTIAMO IL
 PROBLEMA TENENDO IN MENTE LA RICORSIONE, ESSO DIVENTERA' IMMEDIATAMENTE TRATTABILE. LO SPOSTAMENTO DI N DISCHI PORTRA ESSERE
 VISTO COME LO SPOSTAMENTO DI SOLI N-1 DISCHI(E QUINDI LA RICORSIONE) COME SEGUE:
 
 1 MUOVERE N - 1 DISCHI DAL PALETTO 1 AL 2, UTILIZZANDO IL 3 COME AREA DI DEPOSITO TEMPORANEA.
 2 MUOVERE L'ULTIMO DISCO (IL PIU GRANDE ) DAL PALETTO 1 AL PALETTO 3
 3 MUOVERE GLI N - 1 DISCHI DAL PALETTO 2 AL 3, UTILIZZANDO IL PALETTO 1 COME AREA DI DEPOSITO TEMPORANEA.
 
 IL PROCESSO TERMINERA' QUANDO L'ULTIMO COMPITO RICHIEDERA' LO SPOSTAMENTO DI N = 1 DISCHI, OVVEROSIA IL CASO DI BASE. CIO'
 SARA' ESEGUITO SEMPLICEMENTE SPOSTANDO IL DISCO, SENZA LA NECESSITA' DI UN'AREA DI DEPOSITO TEMPORANEA.
 SCRIVERE UN PROGRAMMA CHE RISOLVA IL PROBLEMA DELLE TORRI DI HANOI. UTILIZZATE UNA FUNZIONE RICORSIVA CON QUATTRO PARAMETRI:
 
 1 IL NUMERO DEI DISCHI DA MUOVERE
 2 IL PALETTO SUL QUALE QUESTI DISCHI SARANNO INIZIALMENTE INFILATI.
 3 IL PALETTO SULA QUALE QUESTA PILA DI DISCHI DOVRA' ESSERE SPOSTATA
 4 IL PALETTO CHE DOVRA' ESSERE UTILIZZATO COME AREA DI DEPOSITO
 
 
 IL VOSTRO PROGRAMMA DOVRA' VISUALIZZARE LE ISTRUZIONI PRECISE NECESSARIE PER LO SPOSTAMENTO DEI DISCHI DAL PALETTO DI PARTENZA
 A QUELLO DI DESTINAZIONE. PER ESEMPIO, PER MUOVERE UNA PILA DI TRE DISCHI DAL PALETTO 1  AL PALETTO 3, IL VOSTRO PROGRAMMA
 DOVRA' VISUALIZZARE LA SEGUENTE SERIE DI MOSSE:
 
 1 -> 3(QUESTO SIGNIFICA MUOVERE UN DISCO DAL PALETTO 1 AL PALETTO 3)
 1 -> 2
 3 -> 2
 1 -> 3
 2 -> 1
 2 -> 3
 1 -> 3

 */


#include <stdio.h>

int main(int argc, const char * argv[]) {
    // insert code here...
    int uno = 1 , due = 2, tre = 3, number;
    int n1, n2 = 0, n3 = 0;
    
    
    printf("Inserisci il numero dei dischi: ");
    scanf("%d",&number);
    
    for(n1 = number ; n3 != number;){
        
        if((n1 == 1 && n2 == 0) || (n1 != 0 && n2 != 0 && n3 == 0) || n1 == number){
            printf("\n%d -> %d",uno, tre);
            n1--;
            n3++;
        }else if(n2 == 0 && n3 != 0 && n1 != 0){
            printf("\n%d -> %d",uno, due);
            n1--;
            n2++;
        }else if(n2 != 0 && n3 != 0 && n1 != 0){
            printf("\n%d -> %d",tre , due);
            n2++;
            n3--;
        }else if(n1 == 0 && n2 != 0 && n3 != 0){
            printf("\n%d -> %d",due , uno);
            n2--;
            n1++;
            printf("\n%d -> %d",due , tre);
            n2--;
            n3++;
        }
    }
    printf("\nHello, World!\n");
    return 0;
}
