//
//  main.c
//  Exe6.35
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(RICERCA BINARIA) MODIFICATE IL PROGRAMMA DELLA FIGURA 6.19, IN MODO CHE UTILIZZI UNA FUNZIONE RICORSIVA binarySearch CHE ESEGUA UNA RICERCA BINARIA ALL'INTERNO DEL VETTORE. LA FUNZIONE DOVRÀ RICEVERE, COME ARGOMENTI UN VETTORE DI INTERI E L'INDICE DI INIZIO E DI FINE DEL SOTTOVETTORE IN CUI DOVRÀ ESSERE SEGUITA LA RICERCA. NEL CASO CHE LA CHIAVE DI RICERCA SIA STATA RITROVATA, RESTITUIRETE L'INDICE DEL VETTORE, ALTRIMENTI RESTITUIRETE -1.
*/

