//
//  main.c
//  Exe6.28
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(ELIMINAZIONE DEI DUPLICATI) NEL CAPITOLO 12 ESLPOREREMO LE STRUTTURE DI DATI CON RICERCA BINARIA AD ALTA VELOCITA'. UNA CARATTEREISTICA DEGLI ALVERI DI RICERCA BINARIA E'Ì CHE I VALORI DUPLICATI SARANNO SCARTATI, NELLO STESSO MEMENTO IN CUI GLI ELEMENTI SARANNO INSERITI NELL'ALBERO. QUESTA CARATTERISTICA E' DETTA APPUNTO ELIMINAZIONE DEI DUPLICATI. SCRIVETE UN PROGRAMMA CHE PRODUCA 20 NUMERI CASUALI COMPRESI TRA 1 E 20 . IL PROGRAMMA DOVRA IMMAGAZZINARE IN UN VETTORE TUTTI I VALORI NON DUPLICATI. UTILIZZATE IL VETTORE PIU PICCOLO POSSIBILE PERPORTARE A TERMINE QUESTO COMPITO.
*/
