//
//  main.c
//  Exe6.26
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(lE OTTO REGINE) UN'ALRO PROBLEMA DEGLI APPASSIONATI DEL GIOCO DEGLI SCACCHI È' QUELLO DELLE OTTO REGINE. DETTO SEMPILICEMENTE :
E' POSSIILIE SISTEMARE OTTO REGINE SU UNA SCACCHIERA VUOTA IN MODO CHE NESSUNA DI LORO "ATTACCHI" LE ALTRE, OVVEROSIA IN MODO CHE 
NON CI SIANO DUE REGINE SULLE STESSA RIGA, SULLA MEDESIMA COLONNA O LUNGO LA STESSA DIAGONALE? UTILIZZATE IL TIPO DI RAGGIONAMENTO
SVILUPPATO NELL'ESERCIZIO 6.24 PER FORMULARE UN METODO EURISTICO CHE RISOLVA IL PROBLEMA DELLE OTTO REGINE. ESEGUITE IL VOSTRO PROGRAMMA . (SUGGERIMENTO: SARA' POSSIVILE ASSEGNARE UN VALORE NUMERICO A OGNI CASELLA DELLA SCACCHIERA, IN MODO DA INDICARE IL NUMERO DI QUELLE CHE SARANNO "ESCLUSE", IN UNA SCACCHIERA VUOTA, UNA VOLTA CHE UNA REGINA SARA' STATA SISTEMATA IN QUELLA CASELLA. PER ESEMPIO , A OGNUNO DEI QUATRO ANGOLI SAREBBE ASSEGATO IL VALORE 22, COME MOSTRATO :

* * * * * * * *
* *
*   *
*     *
*       *
*         *
*          *
*            *

UNA VOLTA CHE QUESTI "NUMERI DI ESCLUSIONE" SARANNO STATI SISTEMATI IN TUTTE LE CASELLE 64 CASELLE, UN METODO EURISTICO APPROPRIATO POTRA' ESSERE:SISTEMATE LA PROSSIMA REGINA NELLA CASELLA CON IL NUMERO DI ELIMINAZIONE PIU' BASSO. PER QUALE MOTIVO QUESTA STRATEGIA E' INTUITIVAMENTE ATTRAENTE? 
