//
//  main.c
//  Exe6.37
//
//  Created by Francesco Parrucci on 09/03/19.
//  Copyright © 2019 Francesco Parrucci. All rights reserved.
//
/*(VISUALIZZARE UN VETTORE) SCRIVETE UNA FUNZIONE RICORSIVA printArray CHE RICEVA COME ARGOMENTI UN VETTORE E LA SUA DIMENSIONE E NON RESTITUISCA ALCUN DATO. LA FUNZIONE DOVRÀ TERMINARE LA PROPRIA ELABORAIZONE E RESTITUIRE IL CONTROLLO A QUELLA CHIAMANTE, QUANDO AVRA' RICEVUTO UN VETTORE DI DIMENSIONE 0.
*/
